---
- emacs_required_packages:

# Packages required by vterm
  - cmake
  - libtool
  - gcc

# Packages for opning files from emacs
  # - mpv-mpris # needs the rpm fusion repos
  - feh
  - zathura

# Needed to install some of the language servers
  - nodejs
