- hosts: "{{ test_host | default('localhost') }}"
  become: true

  pre_tasks:

    - name: Upgrade all packages
      dnf:
        name: "*"
        state: latest

  tasks:

    - name: Install the LXDE desktop
      dnf:
        name: "@LXDE Desktop"
        state: present

    - name: Install the LightDM display manager
      dnf:
        name:
          - lightdm
          - lightdm-gtk-greeter
        state: present

    - name: Install Emacs and packages for dotfiles management
      dnf:
        name:
          - emacs
          - git
          - stow
        state: present

    - name: Boot into graphical target by default
      file:
        path: /etc/systemd/system/default.target
        src: /usr/lib/systemd/system/graphical.target
        state: link

    - name: Disable the lxdm display manager
      service:
        name: lxdm
        enabled: no

    - name: Enable LightDM display manager
      service:
        name: lightdm
        enabled: yes

    - name: Use Emacs as the window manager
      lineinfile:
        regexp: "^window_manager="
        line: "window_manager=emacs"
        path: /etc/xdg/lxsession/LXDE/desktop.conf
        state: present
