---
- hosts: "{{ test_host | default('localhost') }}"
  become: true

  vars_files:
    - vars.yml
    - emacs_required_packages.yml
    - exwm_user_packages.yml

  pre_tasks:

    - name: Upgrade all packages
      dnf:
        name: "*"
        state: latest

  tasks:

    - name: Install exwm_user's packages
      dnf:
        name: "{{ exwm_user_packages }}"
        state: present

    - name: Install the LXDE desktop
      dnf:
        name: "@LXDE Desktop"
        state: present

    - name: Install the LightDM display manager
      dnf:
        name:
          - lightdm
          - lightdm-gtk-greeter
        state: present

    - name: Install Emacs and packages for dotfiles management
      dnf:
        name:
          - emacs
          - stow
        state: present

    - name: Install Packages Required by Emacs Packages
      dnf:
        name: "{{ emacs_required_packages }}"
        state: present

    - name: Boot into graphical target by default
      file:
        path: /etc/systemd/system/default.target
        src: /usr/lib/systemd/system/graphical.target
        state: link

    - name: Disable the lxdm display manager
      service:
        name: lxdm
        enabled: no

    - name: Enable LightDM display manager
      service:
        name: lightdm
        enabled: yes

    # - name: Use Emacs as the window manager
    #   lineinfile:
    #     regexp: "^window_manager="
    #     line: "window_manager=emacs"
    #     path: /etc/xdg/lxsession/LXDE/desktop.conf
    #     state: present

    - name: Create exwm user
      user:
        name: "{{ exwm_user_name }}"
        create_home: yes
        append: true
        groups: wheel
        update_password: on_create
        password: "{{ exwm_user_password | password_hash('sha512') }}"

    - name: Create dotfiles dirs so that they dont get created
      file:
        path: "/home/{{ exwm_user_name }}/{{ item }}"
        state: directory
        owner: "{{ exwm_user_name }}"
      with_items:
        - ".emacs.d"
        - ".config"

    - name: Clone the dotfiles repo
      git:
        repo: 'https://github.com/mehdnas/dotfiles.git'
        dest: "/home/{{ exwm_user_name }}/.dotfiles"
        update: no
      become_user: "{{ exwm_user_name }}"

    - name: check if default dotfiles are links
      stat:
        path: "/home/{{ exwm_user_name }}/.bashrc"
      register: bashrc_info

    - name: Ensure default dotfiles are removed
      when: bashrc_info.stat.islnk is defined and not bashrc_info.stat.islnk
      file:
        path: "/home/{{ exwm_user_name }}/{{ item }}"
        state: absent
      become_user: "{{ exwm_user_name }}"
      with_items:
        - ".bash_profile"
        - ".bashrc"
        - ".emacs"

    - name: link dotfiles into home
      command:
        chdir: "/home/{{ exwm_user_name }}/.dotfiles"
        cmd: stow .
      become_user: "{{ exwm_user_name }}"
