---
- exwm_user_name: mehdiexwm
- exwm_user_password: unsafePassword

- second_disk_device: /dev/sdb
- second_disk_partition: /dev/sdb1

- default_fedora_server_vg: fedora_fedorapc
- default_fedora_server_lvm_partition: /dev/sda3

- univ_lv_name: univ
- univ_lv_size: 128G
- univ_lv_fstype: ext4

- root_lv_name: root
- root_lv_size: 64G
